### ISSUE TITLE
Error completing request Arguments:

### ISSUE THREAD

**Issue by SphaeroX** [mix1009/model-keyword#1]
> Error completing request
Arguments: ('lion', '', 'None', 'None', 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 0, 0, 5, False, False, False, '', 1, '', 0, '', True, False, False, '<p style="margin-bottom:0.75em">You can edit extensions/model-keyword/model-keyword-user.txt to add custom mappings</p>', 'keyword prompt', 'keyword1, keyword2', 1.0, 2.0, 'a painting in', 'style', 'picture frame, portrait photo', None) {}
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "D:\stable-diffusion-webui\modules\call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "D:\stable-diffusion-webui\modules\txt2img.py", line 46, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "D:\stable-diffusion-webui\modules\scripts.py", line 317, in run
    processed = script.run(p, *script_args)
  File "D:\stable-diffusion-webui\extensions\stable-diffusion-webui-inspiration\scripts\inspiration.py", line 39, in run
    for file in files:
TypeError: 'NoneType' object is not iterable

**Comment by SphaeroX** [comment]
wuups wrong exgension
