### ISSUE TITLE
LORA's broken

### ISSUE THREAD

**Issue by medledan** [mix1009/model-keyword#27]
LORAs selected by the dropdown menu; and attempting to use created custom keyword mapping results in 'ERROR" in the UI.

NameError: name 'model_ckpt' is not defined
Traceback (most recent call last):
  File "G:\stable-diffusion-webui-current\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "G:\stable-diffusion-webui-current\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "G:\stable-diffusion-webui-current\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "G:\stable-diffusion-webui-current\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "G:\stable-diffusion-webui-current\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "G:\stable-diffusion-webui-current\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "G:\stable-diffusion-webui-current\extensions\model-keyword\scripts\model_keyword.py", line 444, in add_lora_keyword
    lora_keywords = get_lora_keywords(lora_model)
  File "G:\stable-diffusion-webui-current\extensions\model-keyword\scripts\model_keyword.py", line 168, in get_lora_keywords
    kws = _get_keywords_for_lora(lora_model)
  File "G:\stable-diffusion-webui-current\extensions\model-keyword\scripts\model_keyword.py", line 157, in _get_keywords_for_lora
    sim = str_simularity(kw_ckpt[1], model_ckpt)
NameError: name 'model_ckpt' is not defined

**Comment by mix1009** [comment]
Please update to the latest version. The bug was fixed.

**Comment by medledan** [comment]
> Please update to the latest version. The bug was fixed.

Yup, fixed. Thanks!
